Mu2e/Production

MDC2020/POMS/fileNamesGenerator.sh
MDC2020/POMS/getFilename.sh
MDC2020/POMS/loggedMu2e.sh
MDC2020/POMS/printJsonSave.sh
MDC2020/POMS/samListLocations.sh

This PR includes some scripts needed for the POMS campaigns:
- `fileNamesGenerator.sh`: generates the names of the CORSIKA binary files
- `getFilename.sh`: gets the filename and the seed from the fcl files. Needed for stage 1 CORSIKA.
- `loggedMu2e.sh`: saves the Mu2e output in a log file and puts it in a tarball
- `printJsonSave.sh`: saves the JSON file generated by `printJson` and adds the ifdh checksums to the metadata. 
- `samListLocations.sh`: list the locations of the files returned by a SAM query.

Scripts needed for POMS campaign

---

JobConfig/cosmic/S1DSStops.fcl

This PR fixes the fcl file for CRY and CORSIKA production. It removes unused fcl imports and uses the `Common` sequences in the paths.

Removed unused fcl imports, using common sequences

---

JobConfig/beam/BeamResampler_MT.fcl
JobConfig/beam/NeutralsResampler_MT.fcl
JobConfig/beam/POT_MT.fcl
JobConfig/common/epilog_MT.fcl

This PR includes the MT version of `BeamResampler` and `NeutralsResampler`. The MT parameters are specified explicitly and the `epilog_MT.fcl` file is removed.

MT version of resamplers

---

JobConfig/common/artcatSplitLevel1.fcl
JobConfig/common/unsplit.fcl

The script artcatSplitLevel1.fcl behaves like artcat.fcl but it writes the output file with splitLevel : 1.  Previous code used the default, which is splitLevel : 99.  This means fully split since our most nested data products are about 5 or 6 levels deep.
The effect of this change is that the data product payload ( the .obj branch inside the root file) unspilt unit.  
According to Chris Jone, CMS uses splitLevel : 1 if the output is intended to be ready by a production job and they make fully split files if the file is intended to be used for analysis.  The reason is that it saves memory in the running jobs at the cost of increased size on disk.
I tested a MuminusStops file from MDC2020d.  There was an increase in size on disk of 4.2%.  I have not tested the memory savings.

Add artcatSplitLevel1.fcl

---

JobConfig/pileup/prolog.fcl
MDC2020/gen_BeamResampler.sh

This change will eventually change the content of mixin samples, but won't have any immediate effect on nightly validation.

Save only parent and direct SimParticles in pileup

---

JobConfig/beam/prolog.fcl
JobConfig/cosmic/geom_cosmic.txt
JobConfig/cosmic/geom_cosmic_current.txt
README.md

This commit brings the head of main back to the state that it was at commit 742a9d2d, which is the merge of PR#101.   It completes the undo of #99 that was only partially fixed by PR #103 .   After merging this PR, the head should diff cleanly against commit 742a9d2d .
It took 2 mistakes to get here.  PR #99 was  dummy for testing.  The first mistake was that it started from branch Mu2eII_SM21 but I asked to merge it into main.  The second mistake was to merge it, not close it.
In addition to the intended dummy change to README.md PR #99 inadvertently included changes to 3 files:
JobConfig/beam/prolog.fcl
JobConfig/cosmic/geom_cosmic.txt
JobConfig/cosmic/geom_cosmic_current.txt

Complete the undoing of PR #99

---

Scripts/gen_Digitize.sh

I think we should add `Digi` to the description of the dataset, since otherwise the name is the same for the fcl files of the dts stage.

Add Digi to name of the cnf dataset

---

JobConfig/cosmic/S2Resampler.fcl
JobConfig/cosmic/resampling_epilog.fcl

Upon @oksuzian suggestion I added few lines to `S2Resampler.fcl` which give a factor of ~2 speedup. However, I am not exactly sure of what these modifications are actually doing, @oksuzian could you please say a bit more? Thanks.

Speeding up G4 cosmic resampling

---

JobConfig/digitize/OffSpill.fcl
JobConfig/digitize/OnSpill.fcl

This fixes the incompatibility of OnSpill and OffSpill digitization with generate_fcl

Explicitly declare end_path sequence

---

JobConfig/primary/IPAMuminusFlateMinus.fcl
JobConfig/primary/IPAMuminusMichel.fcl
JobConfig/primary/IPAStopParticle.fcl
JobConfig/primary/prolog.fcl
Tests/IPAFlatSteps.fcl
Tests/IPAMichelSteps.fcl

This PR changes the IPA fcl file to be compatible with the new stream where we split the Muminus and Muplus of the IPA output.

Moving from IPAStopResampler to  IPAMuminusStopResampler

---

JobConfig/cosmic/SpillSplitter.fcl

script to pre-select Cosmic events prior to digitization.  Currently this selects signal-like tracks, but in future it should select OnSpill and OffSpill calibration events too, as separate streams.

Cosmicsplit

---

JobConfig/primary/RPC.fcl
JobConfig/primary/RPCExternal.fcl
JobConfig/primary/RPCInternal.fcl
Scripts/gen_Primary.sh

We fix the `gen_Primary.sh` script and the RPC fcl files to generate and mix RPC primaries.

Fixing RPC scripts

---

JobConfig/digitize/offspill_epilog.fcl

This is a temporary fix to address a critical problem digitizing offspill cosmics.  It has minimum impact on the physics simulation of cosmic tracks.  This patch should be replaced with code limiting the noise generation to a narrow window around the cosmic track.

Turn off Crv and Calo noise generation in Offspill digitization

---

Validation/ceSteps.fcl
Validation/muDauSteps.fcl

Dave is turning on database access in more proditions by default.  This means jobs which use these proditions need to have the database configured.  This PR adds the db configuration to more CI test fcl. (already present some places.) The configuration is in `Production/Validation/database.fcl`
which is included many places in validation fcl.

add database to CI tests

---

Validation/nightly/pileup_epilog.fcl

should fix nightly pileup jobs

follow database turn-on

---

JobConfig/digitize/Extracted.fcl

This PR removes the overrides done in Production/JobConfig/digitize/Extracted.fcl for the CRV settings in the extracted position, e.g. CRV lookup tables, light yields, etc. It replaces it by including the Offline settings for the extracted position. This is done in the same way as in Production/JobConfig/reco/Extracted.fcl

use Offline CRV settings for the extracted position

---

Validation/database.fcl
Validation/nightly/ceMix_00.fcl
Validation/nightly/ceMix_01.fcl
Validation/nightly/ceMix_02.fcl
Validation/nightly/ceMix_03.fcl
Validation/nightly/ceMix_04.fcl
Validation/nightly/ceMix_05.fcl
Validation/nightly/ceMix_06.fcl
Validation/nightly/ceMix_07.fcl
Validation/nightly/ceMix_08.fcl
Validation/nightly/ceMix_09.fcl
Validation/nightly/ceMix_10.fcl
Validation/nightly/ceMix_11.fcl
Validation/nightly/ceMix_12.fcl
Validation/nightly/ceMix_13.fcl
Validation/nightly/ceMix_14.fcl
Validation/nightly/ceMix_15.fcl
Validation/nightly/ceMix_16.fcl
Validation/nightly/ceMix_17.fcl
Validation/nightly/ceMix_18.fcl
Validation/nightly/ceMix_19.fcl
Validation/nightly/ceMix_epilog.fcl
Validation/nightly/extracted_00.fcl
Validation/nightly/extracted_01.fcl
Validation/nightly/extracted_02.fcl
Validation/nightly/extracted_03.fcl
Validation/nightly/extracted_04.fcl
Validation/trigger.fcl

Includes new CRV tables and AlignedTrackerSim tables. AlignedTracker reco tables updated to include sim wire offsets. Should be merged at the same time as corresponding Offline PR enabling AlignedTrackerSim db use
It is expected that reco performance (chi2/dof etc.) will look slightly worse in validation.
Note that trigger validation has also been moved to v1_2 but is running still on v1_0 digis.

Updated database version to MDC2020_best v1_2

---

JobConfig/digitize/prolog.fcl

This insulates simulation production from new triggers which are being added experimentally.

Use specific trigger lines to define Signal

---

JobConfig/digitize/prolog.fcl

valCompare of 2000 ceSimReco events has an exact match to before the bug was introduced.

Fix typo in PR 316.

---

JobConfig/digitize/prolog.fcl
JobConfig/primary/prolog.fcl
JobConfig/reco/prolog.fcl

This PR goes with Mu2e/Offline#1306. At the moment, I have done the following (there are some questions):
- added a MakeSurfaceSteps configuration to the primary prolog.fcl
- do we want this done at this early stage? if we are not going to regenerate other DetectorSteps, we could move it into the digitization stage
- added SurfaceStep ```noCompression``` compression at the end of the primary stage
- do we want to do any actual compression at this early stage? I don't think so but let me know if you disagree
- added SurfaceStep compression to the digi and reco stages where we only keep the SurfaceStep if we are keeping the associated SimParticle
- again, I think this is what we want but let me know if not
And some things I haven't done:
- dropped StepPointMCs from any output
- will this …

SurfaceStep Compression Configuration

---

JobConfig/primary/IPAMuminusMichel.fcl
JobConfig/primary/IPAStopParticle.fcl

This PR updates the configuration for `IPAMuminusMichel` primary jobs to use a new (and as-yet unmerged) generator which accommodates heterogeneous materials. The configuration implemented here samples muons which stopped in the IPA volume, and chooses which element the muon captured into according to the relative atomic volumes of carbon and hydrogen. The chosen element then defines the decay-time distribution and DIO spectrum associated with the most-abundant nucleus, respectively. The fcl files produced using `gen_Primary.sh` have been tested to run without error, but depend on https://github.com/Mu2e/Offline/pull/1290.
This PR also makes use of Sophie's `GenFilter` to prefilter out electrons which have trajectory which will never intersect a tracker straw, which will lead to savings …

update IPAMuminusMichel primary generator and prefilter

---

Scripts/gen_Primary.sh

Correct the example invocation. Replace samweb with with samListLocations, as the former gives all locations (tape and persistent, tape first) while the latter preferentialy picks the persistent location if available.
This script needs more work: replacing generate_fcl with mu2ejobdef, etc. I also don't see the need for the 'tag' variable, and I suggest getting rid of the 2nd campaign instance. I think keeping the campaign the same as the one used to generate stopped particles will make it easier for consumers to understand the provenance. These should be addressed in subsequent PRs.

Fix some bugs

---

Validation/trigger.fcl

now generating deep copies of the collection with the objects triggering the event

---

JobConfig/reco/prolog.fcl

While looking at the new EventNtuples, I noticed that sometimes there were different numbers of elements in the ```trk``` branch than in the ```trkmc``` branch:
```
root [2] ntuple->Scan("trk.nhits:trkmc.nhits")
***********************************************
*    Row   * Instance * trk.nhits * trkmc.nhi *
***********************************************
*       15 *        0 *        51 *        48 *
*       15 *        1 *        28 *        28 *
*       15 *        2 *        51 *        48 *
*       15 *        3 *        51 *        27 *
*       15 *        4 *        27 *        31 *
*       15 *        5 *        31 *        47 *
*       15 *        6 *        50 *           *
***********************************************
```
After some debugging, I tracked this down to the fact …

Add missing KKUeM to SelectRecoMC KalSeedMCAssns

---

JobConfig/digitize/epilog.fcl
JobConfig/mixing/epilog.fcl
Validation/cosmicSimReco.fcl

This PR adapts the configuration of the tracker digi maker, i.e. "`makeSD`," to that implemented in https://github.com/Mu2e/Offline/pull/1366. This is a preparatory change for the implementation of runtime-filtering of mixed detector steps.

explicit dts InputTags for tracker digi maker configuration

---

JobConfig/reco/epilog.fcl

To keep the payload size sensible, for now remove the full trajectories. This needs to be revisited.

Save minimal trajectories

---

JobConfig/reco/prolog.fcl

- Apr took over RobustHelixFinder
- DeltaFinder is now the new default for flagging the Compton hits
- added some missing CalPatRec-based sequences

Apr + Delta Finder set as new default instead of RobustHelixFinder + FlagBkgHits

---

JobConfig/beam/SimpleAntiprotons.fcl
JobConfig/primary/AntiprotonStop.fcl
Tests/AntiprotonStopSteps.fcl

Add a production workflow for the simple antiproton gun. This generates antiprotons just upstream of the stopping target, moving downstream. The antiproton stops are saved and then resampled. This may be useful for antiproton reconstruction algorithm development as well as general multitrack algorithm development, but is not meant for antiproton background estimation as the antiproton distributions are not physical.

Add a test stopping target antiproton processing for studies

---

JobConfig/primary/RMCFlatGammaReader.fcl
JobConfig/primary/RMCFlatGammaWriter.fcl
JobConfig/primary/prolog.fcl
Tests/RMCFlatGammaWriter.fcl

Add fcl to produce an RMC photon conversion point dataset using a flat photon energy spectrum. This will be useful for RMC spectrum measurement and unfolding studies using photon pair conversions in the stopping target wires and IPA. It can also be used for estimating the RMC background from asymmetric real photon conversions.

Add flat RMC photon conversion saving production fcl

---

JobConfig/digitize/Extracted.fcl
JobConfig/digitize/MakeSurfaceSteps.fcl
JobConfig/digitize/NoField.fcl
JobConfig/digitize/OffSpill.fcl
JobConfig/digitize/OnSpill.fcl
JobConfig/digitize/Spill.fcl
JobConfig/digitize/epilog.fcl
JobConfig/digitize/prolog.fcl
JobConfig/mixing/Mix.fcl
Validation/ceDigi.fcl
Validation/ceMix.fcl
Validation/cosmicOffSpill.fcl

Small fixes and optimizations for digitizing OffSpill. This now includes MC truth matching for the physics triggers, and lowers the threshold for Triggerable. This will produce substantially more output as the CentralHelix trigger prescale has been set to 1 (formerly 100).

Tweak OffSpill digitization

---

Validation/reco.fcl

Remove an extra Mu2eKinKal prolog include line from the Validation reco fcl, as this throws an error as Offline/TrkPatRec/fcl/Particle.fcl is not yet included. This prolog is already included in JobConfig/reco/Reco.fcl so it is not needed here.

Remove extra Mu2eKinKal prolog include

---

JobConfig/digitize/MakeSurfaceSteps.fcl
JobConfig/digitize/epilog.fcl
JobConfig/digitize/prolog.fcl
JobConfig/primary/AddSurfaceSteps.fcl
Validation/ceSimReco.fcl
Validation/cosmicOffSpill.fcl
Validation/cosmicSimReco.fcl

This PR modifies the digitization script to be compatible with primaries produced after MDC2020ap, where SurfaceSteps replaced StepPointMCs for passive materials. It also adds a script to patch primaries produced prior to that.

Change default config to be processing dts with SurfaceSteps

---

JobConfig/digitize/prolog.fcl
JobConfig/digitize/trigSequencesMC.fcl
JobConfig/mixing/Mix.fcl
JobConfig/mixing/MixTrigVal.fcl
JobConfig/mixing/prolog.fcl

simple renaming of DAQ module instances according to https://github.com/Mu2e/Offline/pull/1434

renaming daq decoders processing module

---

JobConfig/primary/RMCExternal.fcl

Increase the MC filtering in the RMC external simulation to more closely match the generation energy threshold. As the photon energy range only goes down to 85 MeV, the electron/positron spectrum shape below this becomes unphysical due to the missing photons below 85 MeV. For an 80 MeV/c primary filter threshold, I found 12 events in a 100k simulation passed the primary particle filtering (~0.01-0.02%). For a 3 billion RMC photon generation (around the Run 1 expectation) this would lead to about 60k accepted events overall.

Increase MC filtering threshold on external RMC generation

---

JobConfig/digitize/OnSpill_epilog.fcl

We renamed the `apr_lowP_stopTarg_multiTrk` trigger path to use `highP` in the name, as the path uses an 80 MeV/c threshold on both tracks (which corresponds to the `highP` trigger).

Rename low p multi-trk --> high p multi trk due to high threshold used

---

JobConfig/primary/RPC.fcl
JobConfig/primary/RPCExternalPhysical.fcl
JobConfig/primary/RPCInternalPhysical.fcl
JobConfig/primary/RPCPhysical.fcl
JobConfig/primary/TargetPiStopParticle.fcl

Generate physical RPC spectra from infinite pion lifetime samples for use in MDS campaigns. This is in connection with https://github.com/Mu2e/Offline/pull/1479

Add production scripts for physical RPC spectra

---

JobConfig/primary/RPCPhysical.fcl

The accept/reject filter module used in the physical RPC productions was updated in PR https://github.com/Mu2e/Offline/pull/1483. This updates the configuration parameters, without changing the simulation results.

Update accept/reject filter configuration

---

JobConfig/digitize/DTSfilter.fcl
JobConfig/digitize/Digitize.fcl
JobConfig/digitize/NoField.fcl
JobConfig/digitize/OffSpill.fcl
JobConfig/digitize/OnSpill.fcl
JobConfig/digitize/OnSpill2Trk.fcl
JobConfig/digitize/prolog.fcl
JobConfig/mixing/Mix.fcl
JobConfig/mixing/Mix2Trk.fcl

Add an initial idea of a two-track "triggerable" MC selection to the digitization. This is off by default, where I've added specific fcl with this turned on for two track studies. This would target physics like photon conversions (RMC, RPC) and antiproton events. The threshold is initially very low as we study RMC conversions and how well we can trigger on events like coincident ~60 MeV/c + ~35 MeV/c electron-positron pairs. We will only generate these processes to begin with, but may turn this on in general as we turn on corresponding triggers.

Add a triggerable selection for two track events

---

JobConfig/common/epilog.fcl

This change allows Production jobs to override the default geometry. It currently has no effect.

Override the default geometry from Offline
