JobConfig/cosmic/S1DSStops.fcl, JobConfig/cosmic/S2Resampler.fcl, JobConfig/cosmic/prolog.fcl, JobConfig/primary/prolog.fcl
This PR should fix the S2 cosmic resampling and includes the correct `PrimaryPath`.
=> Resampling offset

JobConfig/cosmic/S2ResamplerHigh.fcl, JobConfig/cosmic/S2ResamplerLow.fcl
This PR fixes the `S2ResamplerHigh.fcl` and `S2ResamplerLow.fcl` fcl files for cosmic resampling.
=> Fixing high and low cosmic resampler fcl files

Validation/potSim.fcl
Buffer the beam script to allow overriding printout, seed, etc.
=> Call beam script

CampaignConfig/mdc2020_corsika.cfg
Removed unused lines in the POMS configuration files and fixed the name of the S2 samples
=> Fixed POMS configuration names

CampaignConfig/mdc2020_beam.cfg, CampaignConfig/mdc2020_beam.ini
This PR adds the MuonStopSelector stage to the POMS campaign
=> Added MuonStopSelector stage

Validation/potSim.fcl
- restore current geometry - all Validation except reco should run on the current geometry, to test the head
- remove inoperative val output file name
=> restore current geometry, remove file name

CampaignConfig/mdc2020_beam.cfg, CampaignConfig/mdc2020_beam.ini, CampaignConfig/mdc2020_corsika.cfg, CampaignConfig/mdc2020_corsika.ini, JobConfig/beam/EleBeamResampler_MT.fcl, JobConfig/beam/MuBeamResampler_MT.fcl, JobConfig/cosmic/S2Resampler.fcl, MDC2020/POMS/fileNamesGenerator.sh, MDC2020/POMS/printJsonSave.sh
This PR includes new versions of the beam and CORSIKA campaigns.
=> Campaigns fixes

JobConfig/beam/EleBeamResampler_MT.fcl, JobConfig/beam/MuBeamResampler_MT.fcl, JobConfig/mixing/NoPrimary.fcl
fix a few more missed include shifts
=> more include shifts

CampaignConfig/mdc2020_mix.cfg, CampaignConfig/mdc2020_mix.ini
This PR includes a campaign that does mixing and digitization for NoPrimary and CeEndpoint. Can be easily expanded in the future to include more primaries.
=> Mix and digi campaign

CampaignConfig/mdc2020_beam.cfg, MDC2020/POMS/catAndShuf.sh
This PR fixes the number of jobs for the 1% campaign and contains a bug fix for the script that does the shuffling of the input files for the Flash output concatenation.
=> Number of jobs fix

CampaignConfig/mdc2020_beam.cfg, CampaignConfig/mdc2020_mix.cfg, CampaignConfig/mdc2020_mix.ini, MDC2020/gen_Mix.sh
This PR contains a series of bug fixes in the Mix MDC2020 campaign, including setting the `DbService.purpose` to MDC2020i.
=> Mix campaign fixes

JobConfig/beam/BeamSplitter.fcl, JobConfig/beam/CreateSimEfficiency.sh, JobConfig/beam/MuBeamResampler.fcl, JobConfig/mixing/Mix.fcl, JobConfig/primary/FlateMinus.fcl, JobConfig/primary/FlatePlus.fcl, JobConfig/primary/flateplus.fcl, JobConfig/reco/RecoNoMC.fcl, MDC2020/gen_FlateMinus.sh, MDC2020/gen_FlatePlus.sh, MDC2020/gen_Mix.sh
Also improve comments and whitespace.
=> Fix mixing script

CampaignConfig/mdc2020_mix.cfg, CampaignConfig/mdc2020_mix.ini, JobConfig/primary/IPAStopParticle.fcl, JobConfig/primary/IPAStopsFlat.fcl, JobConfig/primary/IPAStopsMichel.fcl, JobConfig/primary/StopParticle.fcl, JobConfig/primary/TargetStopParticle.fcl, MDC2020/gen_Mix.sh
This PR includes two main changes:
- `FlateMinus` and `NoPrimaryPBI` stages added to the POMS configuration
- Fixed `IPAStop` fcl files
=> Mix campaign improvements

CampaignConfig/mdc2020_corsika.cfg, CampaignConfig/mdc2020_corsika.ini, JobConfig/primary/prolog.fcl
This PR includes few small fixes to the POMS CORSIKA campaign and reintroduces the `CosmicLivetime` data product in the list of kept products.
=> CORSIKA campaign fixes 

JobConfig/mixing/CreatePBISequence.fcl
Bug fix with correct PBISequence label
=> Fixed PBI module label

CampaignConfig/mdc2020_beam.cfg, CampaignConfig/mdc2020_corsika.cfg, CampaignConfig/mdc2020_corsika.ini, CampaignConfig/mdc2020_cry.cfg, CampaignConfig/mdc2020_cry.ini, CampaignConfig/mdc2020_noprimary.cfg, CampaignConfig/mdc2020_prolog.cfg, JobConfig/cosmic/S2ResamplerCORSIKA.fcl, JobConfig/cosmic/S2ResamplerCRY.fcl
Small refactoring and moving concatenation after resampling for CORSIKA and CRY
=> Refactoring for CORSIKA and beam campaigns

CampaignConfig/mdc2020_corsika.cfg, CampaignConfig/mdc2020_corsika.ini, CampaignConfig/mdc2020_cry.cfg, CampaignConfig/mdc2020_noprimary.cfg, JobConfig/cosmic/S2Resampler.fcl
I am fixing the output of the cosmic resampling (Cosmic and CosmicLoose) and specifying the `genCounter::Primary` data product for the cosmic livetime mixer.
=> Output fixes

CampaignConfig/mdc2020_beam.cfg
POMS configuration updates for the beam 10% campaign.
=> Beam 10% campaign

Scripts/CreateSimEfficiency.sh
This PR adds a quick fix to `CreateSimEfficiency.sh` to be able to manage datasets with several thousands of files.
=> Chunksize for SimEfficiency

JobConfig/pileup/prolog.fcl, JobConfig/primary/prolog.fcl
This is the PR that goes with  Mu2e/Offline#669
=> CompressDetStepMC updates for multiple input SimParticleCollections

JobConfig/mixing/LowIntensity.fcl, Scripts/gen_Mix.sh
=> Add low intensity mixing

JobConfig/cosmic/NoField.fcl, JobConfig/cosmic/S1DSStops.fcl, JobConfig/cosmic/S2Resampler.fcl, JobConfig/cosmic/S2Resampler_MT.fcl
Adding MT to S1 and S2 cosmic FCL files.
=> Multi-threaded cosmic FCL files

JobConfig/validation/stoppedMuonsSingleStage.fcl
Small tweaks to the stopped muon validation job.
=> Remove a wrong comment and tweak cuts for stopped muon validation job.

JobConfig/mixing/EarlyMixins.fcl, JobConfig/mixing/prolog.fcl, Scripts/gen_Mix.sh
Complete early mixing implementation.  Extend mixed collection descriptions to include beam intensity and (early) mixing if needed.  Subsystem reviewers, please examine the timing configuration for digitization.
=> Early Mixing

JobConfig/cosmic/SpillSplitter.fcl, JobConfig/digitize/prolog.fcl, Scripts/gen_Mix.sh
Refine mixing parameters.  Update streams for OffSpill.  Add script for splitting cosmics
=> mixing updates

JobConfig/cosmic/SpillSplitter.fcl, Scripts/gen_Mix.sh
Using a fresh branch and commit to get these changes back in.
=> Add back reverted changes in a fresh commit

Scripts/gen_Reco.sh
Small fixes to the reco script.
=> Updated gen_Reco.sh script

Scripts/gen_Reco.sh
Saving the DB purpose and version in the FCL files used for reconstruction
=> Saving DB info for reco FCL files

Scripts/gen_Digitize.sh, Scripts/gen_Mix.sh
Updates about database purposes and versions. Also fixed documentation.
=> Updating digi and mixing scripts

JobConfig/digitize/epilog.fcl, JobConfig/mixing/NoPrimary.fcl, JobConfig/reco/epilog.fcl, Scripts/gen_Digitize.sh, Scripts/gen_Mix.sh, Scripts/gen_Reco.sh, Validation/ceDigi.fcl, Validation/ceMix.fcl, Validation/ceSimReco.fcl, Validation/cosmicOffSpill.fcl, Validation/cosmicSimReco.fcl, Validation/database.fcl, Validation/potSim.fcl, Validation/reco.fcl
This reconfigures extends gen_Mix, Reco, Digitize scripts to add Db or printout.  Also added specific conditions use in reco and digitization epilog.
Also make NoPrimary Untriggered…stream save all events
=> Use DB in digitization and reco

Scripts/gen_Reco.sh, Validation/ceSimReco.fcl, Validation/ceSteps.fcl, Validation/cosmicOffSpill.fcl, Validation/cosmicSimReco.fcl, Validation/database.fcl
Also fix Reco comment and output directory
=> Change validation purpose to 'best'. 

JobConfig/beam/MuBeamSplitter.fcl
This FCL file splits the muon beam output into mu+ and mu-.
=> Added MuBeam splitter FCL file

Scripts/gen_Digitize.sh, Scripts/gen_Reco.sh
This PR allows non-production users to run digi and reco.
=> Adding the option of having custom owners

JobConfig/reco/epilog.fcl, JobConfig/reco/prolog.fcl, Scripts/gen_BeamSplitter.sh, Scripts/gen_MuonStops.sh, Scripts/gen_POT.sh, Scripts/gen_POT_infinite.sh, Scripts/gen_PionBeamSelector.sh
=> Consolidate

Validation/ceSimReco.fcl
BTW, this fcl get this field from Services.Sim but that is superseded by Production/JobConfig/digitize/epilog.fcl.  I wouldn't naturally expect that epilog to be be setting the b field file.
=> use bfgeom_v01.txt in ceSimReco

JobConfig/pbar/vertex_s1.fcl
follows Mu2e/Offline#878  Probably should be merged after that
=> follow pdgid string in Offline

CampaignConfig/mdc2020_beam.cfg, CampaignConfig/mdc2020_beam.ini, CampaignConfig/mdc2020_ceendpoint.ini, CampaignConfig/mdc2020_ceplusendpoint.ini, CampaignConfig/mdc2020_corsika.cfg, CampaignConfig/mdc2020_corsika.ini, CampaignConfig/mdc2020_corsikamix.cfg, CampaignConfig/mdc2020_corsikamix.ini, CampaignConfig/mdc2020_cry.cfg, CampaignConfig/mdc2020_cry.ini, CampaignConfig/mdc2020_flateminus.ini, CampaignConfig/mdc2020_flateplus.ini, CampaignConfig/mdc2020_ipaflat.ini, CampaignConfig/mdc2020_ipamichel.ini, CampaignConfig/mdc2020_noprimary.cfg, CampaignConfig/mdc2020_noprimary.ini, CampaignConfig/mdc2020_prolog.cfg
Removed the paths to local and replaced by the latest SimJob. There are still options to run local jobs as these are there by design but the default includes are now pointing to the SimJob
=> changed paths to scripts

JobConfig/reco/Extracted.fcl, JobConfig/reco/NoField.fcl, JobConfig/reco/prolog.fcl
Straight line production fcl in nominal and extracted position. Depends on mu2e/Offline#907
=> Added extracted straight line reco

JobConfig/common/artcat.fcl, JobConfig/ensemble/reco-mcdigis-trig.fcl, JobConfig/pbar/resample_vertex_s2.fcl, Validation/ceSimReco.fcl
* fully addresses Mu2e/Production#134
* all changes are commented or fcl is obsolete, so no changes to Validation or production
=> fix small residual fcl paths

Scripts/gen_Primary.sh
Fixed a few typos in this file. Now it runs without error
=> fixed primary.sh

JobConfig/reco/Reco.fcl, JobConfig/reco/offspill_epilog.fcl
Follow changes in ComboHit reconstruction
=> Fixes for ComboHit changes

CampaignConfig/mdc2020_primary.cfg, Scripts/gen_Digitize.sh, Scripts/gen_Mix.sh, Scripts/gen_Primary.sh, Scripts/gen_Reco.sh
Further edits to make usage function more informative following discussion in comp/soft
=> Script updates

JobConfig/digitize/OnSpill.fcl, JobConfig/digitize/prolog.fcl, Scripts/gen_Digitize.sh, Scripts/gen_Mix.sh
Add pions to untriggered list.  Set prescale to 1.0
=> OnSpill Untriggered adjustments

CampaignConfig/mdc2020_primary.cfg, Scripts/gen_Digitize.sh, Scripts/gen_Mix.sh, Scripts/gen_Reco.sh
Note this is an intermediate step, mdc2020_primary.cfg paths will return to CVFMS once test are finished
=> updated scripts and cfg

JobConfig/reco/Extracted.fcl, JobConfig/reco/offspill_epilog.fcl, Processing/CosmicTrackDiag.fcl, Processing/StraightLineReco.fcl, Processing/vst_epilog.fcl, Processing/vstdata_epilog.fcl
=> Updated for cosmic TrackerConditions changes

JobConfig/digitize/prolog.fcl, JobConfig/reco/prolog.fcl
This PR goes with Mu2e/Offline#973 and updates the prolog.fcl with the new fhicl parameter names
=> Allow for Multiple CrvCoincidenceCollections

JobConfig/ensemble/prolog_reco.fcl, JobConfig/ensemble/reco-mcdigis-trig.fcl, JobConfig/reco/IPA-Michel.fcl, JobConfig/reco/prolog.fcl, Scripts/gen_Reco.sh, Validation/reco.fcl
This PR finishes the migration to KinKal
=> Remove BTrk fits from production and validation

Validation/reco.fcl
=> Fix reco validation

JobConfig/reco/prolog.fcl
This PR goes with Offline PR 979
=> Follow KK instance name change

JobConfig/reco/prolog.fcl
should be merged before the Offline PR
=> removing TimeMap references (8)

JobConfig/digitize/prolog.fcl, JobConfig/reco/prolog.fcl
=> remove timemaps

Scripts/gen_Reco.sh
Simple addition that adds an option in case we want to rerun reco with a different db version compared to the digis.
=> Add option to change reco DB version

JobConfig/reco/epilog.fcl, JobConfig/reco/prolog.fcl
This PR goes with Mu2e/Offline#1047
=> Move crv mc assns

JobConfig/reco/Reco.fcl, JobConfig/reco/drop_trigger.fcl, JobConfig/reco/prolog.fcl
Drop trigger products in reco.  Remove references to StrawHitFlagCollection
=> ComboHitCollection Migration

JobConfig/digitize/OffSpill.fcl
=> Prescale RMC trigger

JobConfig/reco/OffSpill.fcl, JobConfig/reco/prolog.fcl
=> Added OffSpill reco

JobConfig/pileup/prolog.fcl, JobConfig/primary/prolog.fcl
add stuff to manage particle stops in the ST supporting wires
=> particle stops in the ST supporting wires

Validation/muDauSteps.fcl
Will fix CI problem with muDauSteps and ceMix with Mu2e/Offline#1183
=> add run number for database access

JobConfig/digitize/DTSfilter.fcl, JobConfig/digitize/Digitize.fcl, JobConfig/digitize/Extracted.fcl, JobConfig/digitize/NoField.fcl, JobConfig/digitize/OffSpill.fcl, JobConfig/digitize/OnSpill.fcl, JobConfig/digitize/prolog.fcl, JobConfig/mixing/Mix.fcl, JobConfig/mixing/prolog.fcl, Validation/ceDigi.fcl, Validation/cosmicOffSpill.fcl, Validation/trigger.fcl
This PR integrates the use of the mu2e_trig_config repo.
=> updated paths of the trigger config files

Validation/trigger.fcl
The file was tested locally with the NoPrimary1BB sample
=> fixed trigger config

JobConfig/digitize/prolog.fcl, JobConfig/ensemble/SamplingInput.fcl, JobConfig/mixing/MixTrigVal.fcl, Validation/nightly/ceMix_00.fcl, Validation/nightly/ceMix_01.fcl, Validation/nightly/ceMix_02.fcl, Validation/nightly/ceMix_03.fcl, Validation/nightly/ceMix_04.fcl, Validation/nightly/ceMix_05.fcl, Validation/nightly/ceMix_06.fcl, Validation/nightly/ceMix_07.fcl, Validation/nightly/ceMix_08.fcl, Validation/nightly/ceMix_09.fcl, Validation/nightly/ceMix_10.fcl, Validation/nightly/ceMix_11.fcl, Validation/nightly/ceMix_12.fcl, Validation/nightly/ceMix_13.fcl, Validation/nightly/ceMix_14.fcl, Validation/nightly/ceMix_15.fcl, Validation/nightly/ceMix_16.fcl, Validation/nightly/ceMix_17.fcl, Validation/nightly/ceMix_18.fcl, Validation/nightly/ceMix_19.fcl, Validation/trigger.fcl
- fixed trigger names used in a few `SelecEvents :[`
- switched to the trigger validation menu in the nightly jobs
=> fixed trigger names and added the trigMenu includes to the validation jobs

JobConfig/digitize/cosmic_epilog.fcl, JobConfig/digitize/prolog.fcl, Scripts/gen_Digitize.sh
Add TriggerInfo back to the payload.  Fix output stream name for Extracted, and don't include cosmic epilog (Extracted has no S2)
=> Small fixes

Validation/cosmicOffSpill.fcl, Validation/reco.fcl
This should resolve the problem with CI using a run number outside what the database tables expect.
=> Use correct run number in CI and use standard script

Validation/database.fcl
Update to v1_3 to fix TrkAlignStraw values which accidentally had double the variation intended (same as in v1_0)
=> Update db version

JobConfig/pileup/STM/BeamToVD101.fcl, Scripts/gen_BeamToVD101.sh, Scripts/gen_STMResampler.sh
The previous directory for the STM pileup scripts was `Production/JobConfig/pileup`, it's now `Production/JobConfig/pileup/STM`
=> Minor fcl file fixes

JobConfig/digitize/prolog.fcl, JobConfig/pileup/prolog.fcl, JobConfig/validation/mixPointsDump.fcl
This depends on Offline PR https://github.com/Mu2e/Offline/pull/1300
=> Follow CommonMC prolog change

JobConfig/ensemble/python/normalizations.py
- bug discovered in normalization script, this is a fix
=> fix normalization

.gitignore, JobConfig/digitize/MakeSurfaceSteps.fcl, JobConfig/primary/prolog.fcl, JobConfig/reco/MakeSurfaceSteps.fcl
Follow change to make parameter name less misleading. This PR is paired with Offline 1336
=> Follow parameter name change

JobConfig/reco/prolog.fcl
=> KKOffSpill takes LineFinder input

Validation/database-v1_1-compat.fcl
For validation scripts using v1_1 or older digis
=> Add fcl for backwards compatibility

JobConfig/reco/RecoNoMC.fcl
=> Fix for NoMC reco

Scripts/gen_Resampler.sh, data/primary_rmc.json
It also prevents running the script from the cvmfs dev area
=> No need to check for cvmfs directory. 

JobConfig/digitize/DTSfilter.fcl, JobConfig/digitize/Digitize.fcl, JobConfig/digitize/NoField.fcl, JobConfig/digitize/OnSpill.fcl, JobConfig/digitize/Spill.fcl, JobConfig/digitize/prolog.fcl, JobConfig/digitize/trigSequencesMC.fcl, JobConfig/mixing/Mix.fcl, JobConfig/mixing/MixTrigVal.fcl, Pass1/Wideband/CrvPass1_wideband1module.fcl, Pass1/Wideband/CrvPass1_widebandExtracted.fcl, Validation/trigger.fcl
am doing the same in the mu2e-trig-config package as well.
=> changing mu2e_trig_config to mu2e-trig-config

Validation/nightly/extracted_00.fcl, Validation/nightly/extracted_01.fcl, Validation/nightly/extracted_02.fcl, Validation/nightly/extracted_03.fcl, Validation/nightly/extracted_04.fcl, Validation/nightly/reco_00.fcl, Validation/nightly/reco_01.fcl, Validation/nightly/reco_02.fcl, Validation/nightly/reco_03.fcl, Validation/nightly/reco_04.fcl, Validation/nightly/reco_05.fcl, Validation/nightly/reco_06.fcl, Validation/nightly/reco_07.fcl, Validation/nightly/reco_08.fcl, Validation/nightly/reco_09.fcl
Previous update to validation fcl changed output file names as a side effect, this brings them back to previous.
=> update nightly validation file names

JobConfig/reco/prolog.fcl
Loosen some cuts introduced for OffSpill selection that were adversely affecting OnSpill reco efficiency
=> Fix for OnSpill efficiency

Pass1/Wideband/CrvPass1_widebandExtracted.fcl
This merge has to wait for the next release of artdaq_core_mu2e and Offline.
=> collecting DAQ errors

JobConfig/mixing/prolog.fcl, Validation/ceMix.fcl
This follows Offline PR [1445](https://github.com/Mu2e/Offline/pull/1445)
=> Update mixing configuration to follow Offline

Pass1/Calo/VST.fcl
capturing some basics from Paolo
=> prototype pass1 for calo vst

JobConfig/common/artcat.fcl, JobConfig/digitize/StripMC.fcl, Scripts/POMS/samDatasetsSummary.sh
Otherwise, it may result in an issue described in INC000001194060.
=> Set fastCloning to false by default in artcat and StripMC fcls

CampaignConfig/mdc2020_digireco.cfg, Scripts/json2jobdef.sh, data/merge_filter.json, data/resampler.json, data/stage1.json
Unified generator for Stage1, Stage2(Resa…mpler, Primaries), or Merge jobs via JSON
Examples:
json2jobdef.sh --json data/resampler.json --desc FlatePlus
json2jobdef.sh --json data/stage1.json --desc PiBeam
json2jobdef.sh --json data/merge_filter.json --desc ensembleMDS1eOnSpillTriggered-noMC
=> Addition of json2jobdef.sh

.gitignore, JobConfig/reco/OnSpill.fcl, JobConfig/recoMC/OnSpill.fcl
Remove LoopHelix filtering when processing OnSpilll data.
=> remove OnSpill filtering

JobConfig/digitize/AddSurfaceSteps.fcl, JobConfig/digitize/Digitize.fcl, JobConfig/digitize/prolog.fcl, JobConfig/reco/Reco.fcl, JobConfig/recoMC/Reco.fcl, Scripts/nightly_jobs.sh, Validation/nightly/CeMix/build_jobs.sh, Validation/nightly/CeSimReco/build_jobs.sh, Validation/nightly/CeSimReco/digitize.fcl, Validation/nightly/CeSimReco/reconstructCeMinus.fcl, Validation/nightly/CeSimReco/reconstructCePlus.fcl, Validation/nightly/CosmicSimReco/S2.fcl, Validation/nightly/CosmicSimReco/build_jobs.sh, Validation/nightly/CosmicSimReco/digitizeOffSpill.fcl, Validation/nightly/CosmicSimReco/digitizeOnSpill.fcl, Validation/nightly/CosmicSimReco/reconstructOffSpill.fcl, Validation/nightly/CosmicSimReco/reconstructOnSpill.fcl, Validation/nightly/MDS/build_jobs.sh, Validation/nightly/MDS/digitize.fcl, Validation/nightly/MDS/digitize.sh, Validation/nightly/MDS/reconstruct.fcl, Validation/nightly/Pileup/build_jobs.sh, Validation/nightly/Trigger/build_jobs.sh, Validation/nightly/Trigger/trigger.fcl
=> Add MDS validation

JobConfig/primary/RMC.fcl, JobConfig/primary/RMCFlatInternal.fcl
This requires https://github.com/Mu2e/Offline/pull/1568 to run
=> Add flat RMC internal fcl, only sample one muon per event
